name: Test

on: push

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
    
       - name: Set up Python version
         uses: actions/setup-python@v1
         with:
           python-version: '3.7'
    
       - name: Create and start virtual environment
         run: |
           python -m venv venv
           source venv/bin/activate
              
       - name: Update pip
         run: python -m pip install --upgrade pip
         
       - name: run Python
         run: python hello.py

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Start containers
        run: docker compose -f "docker-compose.yml" up -d --build
      
      - name: Stop containers
        run: docker-compose -f "docker-compose.yml" down
