name: Test

on: push

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python my_script.py

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Start containers
        run: docker compose -f "docker-compose.yml" up -d --build
      
      - name: Stop containers
        run: docker-compose -f "docker-compose.yml" down
